### ISSUE TITLE
версия 1.1.3

### ISSUE THREAD

**Issue by ZloyBarsuk** [uranum/yii2-excel-exchange#1]
Кусок говна! Ты хоть проверяешь свой код на работоспособность перед тем. как сюда его пилить? Алиасы не работают, айди можели при импорте берется за основу id, а если у кого-то  поле первичного ключа не  называется id? Допиливать и допиливать!!!!!

**Comment by uranum** [comment]
Ослики идут домой, в зоопарк... Кто-то загончик забыл закрыть?
